# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9743ee39eb325a36313284d832b97945"
name = "Bloomreach Discovery v2"
application_url = "https://bloomreach-discovery-v2-c85471a4033c.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes"

[auth]
redirect_urls = [
  "https://bloomreach-discovery-v2-c85471a4033c.herokuapp.com/auth/callback",
  "https://bloomreach-discovery-v2-c85471a4033c.herokuapp.com/auth/shopify/callback",
  "https://bloomreach-discovery-v2-c85471a4033c.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[webhooks.privacy_compliance]
customer_deletion_url = "https://bloomreach-discovery-v2-c85471a4033c.herokuapp.com/webhooks/customer_deletion"
customer_data_request_url = "https://bloomreach-discovery-v2-c85471a4033c.herokuapp.com/webhooks/customer_request"
shop_deletion_url = "https://bloomreach-discovery-v2-c85471a4033c.herokuapp.com/webhooks/deletion"
