# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9743ee39eb325a36313284d832b97945"
name = "Bloomreach Discovery v2"
application_url = "https://shopify-discovery-connector-v2.herokuapp.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes"

[auth]
redirect_urls = [
  "https://shopify-discovery-connector-v2.herokuapp.com/auth/callback",
  "https://shopify-discovery-connector-v2.herokuapp.com/auth/shopify/callback",
  "https://shopify-discovery-connector-v2.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
