name = "bloomreach-web-pixel"
type = "web_pixel_extension"
runtime_context = "strict"

[customer_privacy]
analytics = true
marketing = true
preferences = false
sale_of_data = "enabled"

[settings]
type = "object"

[settings.fields.account_id]
name = "Account ID"
description = "Bloomreach Discovery Account ID"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]
